sudo: false
language: node_js
node_js: 10.16.3
install:
  - npm install
branches:
  only:
    - blog-source # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: blog-html
  local-dir: public