comments:
  service: beaudar
  beaudar:
    repo: Throokie/blog_commit

#主导航栏
sidebar:
  menu:
    post: '[btn.blog](/)'
    wiki: '[btn.wiki](/wiki/)'
    notes: '[笔记](/notes/)'
    more: '[更多](/more/)'